apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-portfolio
  template:
    metadata:
      labels:
        app: ai-portfolio
    spec:
      containers:
        - name: ai-portfolio
          image: dasmat/ai-portfolio:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
